### ISSUE TITLE
[docs] How to setup nodemailer

### ISSUE THREAD

**Issue by merelinguist** [benawad/fullstack-graphql-airbnb-clone#11]
Hi Ben, thanks for adding the docs - super helpful :). Trying to set this up, one thing I got stuck on was how to get emails to send. Any advice would be much appreciated.

**Comment by benawad** [comment]
Do you not get the link in your terminal? Or are you wanting the email to actually send?

**Comment by benawad** [comment]
You just need to switch out the transport. Right now we have a test one in. https://nodemailer.com/transports/

**Comment by merelinguist** [comment]
Thanks!
