### ISSUE TITLE
Adding a Header

### ISSUE THREAD

**Issue by captDaylight** [benawad/fullstack-graphql-airbnb-clone#16]
Hey love what you built here. There aren't a lot of apollo examples that don't store a jwt token in localstorage and use that to determine if a user is logged in, so glad to see a solution using sessions!
 
I'm curious to see how you would handle something like a `Header` component that's _outside_ of your AuthRoutes, but that reflects the current auth state by either showing Login/Register or Logout. So when I log in, the header then knows to update and show the logout link.

so something like:

```
<ApolloProvider client={client}>
  <Header />
  <Routes />
</ApolloProvider>
```

**Comment by captDaylight** [comment]
Ya, I guess the problem I come to is that I have something similar to your me query in my header. Then, when I log in and get the user object returned, it for some reason is not triggering the me query in the header to update. Since the me query isn't associated with a user id, I think it won't know to refetch. Does that make sense?

**Comment by benawad** [comment]
Yeah, so what you need to do is update the me query in the cache after the login mutation

**Comment by captDaylight** [comment]
Cool, that's what I figured, but I'm not sure how to do that the Apollo way. Do you have an example of a remote mutation updating the cache for another remote query?

**Comment by benawad** [comment]
Here's the docs on it: https://www.apollographql.com/docs/react/essentials/mutations.html#update

Here's an example of me using it in a project: https://github.com/benawad/slack-clone-client/blob/2588510aeb4ed9127ae64eb21072307468dae79b/src/components/AddChannelModal.js#L76

**Comment by captDaylight** [comment]
thx 🙇‍♂️ ! exactly what I was looking for.
