### ISSUE TITLE
Blank page when launching dev

### ISSUE THREAD

**Issue by JamesLawton** [benawad/fullstack-graphql-airbnb-clone#26]
I have followed the steps listed in the README and launch the server and frontend with yarn start. However, when I navigate to localhost:3000, nothing is displayed. There's no errors in the console either, however I can see the GraphQL server on localhost:4000. I can confirm that the postgres DB and redis are running. 

Any ideas on what the problem could be?

**Comment by benawad** [comment]
That's expected, I didn't make a homepage for this project, you can see the routes here: https://github.com/benawad/fullstack-graphql-airbnb-clone/blob/master/packages/web/src/routes/index.tsx

**Comment by JamesLawton** [comment]
Ah, perfect! Thanks.
