### ISSUE TITLE
TypeORM synchronize option ormconfig.json

### ISSUE THREAD

**Issue by exwyezed** [benawad/fullstack-graphql-airbnb-clone#29]
Hey Ben,

Do you recommend to use `"synchronize": true` in production and `"synchronize": false` in development and run manually the migrations locally?

Is it OK? can you explain why you're doing it like that?

https://github.com/benawad/fullstack-graphql-airbnb-clone/blob/8bbca2d30a6c67e9fa27f9fc4c5973cc2b075dd1/packages/server/ormconfig.json

**Comment by benawad** [comment]
I don't think that setting is being used in production.

Once you deploy your application, I recommend setting synchronize to false and running migrations to update stuff
