### ISSUE TITLE
WebSocket is closed before the connection is established.

### ISSUE THREAD

**Issue by goodza** [benawad/fullstack-graphql-airbnb-clone#34]
After `yarn start` web client (localhost:3000) has the error in console:

`WebSocket connection to 'ws://localhost:4000/' failed: WebSocket is closed before the connection is established.`

Though the server is running.

**Comment by benawad** [comment]
is this when you cloned my code?

**Comment by goodza** [comment]
Yes. Redis, Postgres, and Server are running but web client throws error.

**Comment by goodza** [comment]
The problem appears with ws-handshake when there are 2 or more unclosed tabs of localhost:3000
