### ISSUE TITLE
Module not found: Can't resolve 'apollo-client'

### ISSUE THREAD

**Issue by Je12emy** [benawad/fullstack-graphql-airbnb-clone#38]
Following Part 8 I am unable to start the web site, I'm getting this error after executing `Yarn start`
```
/home/foo/AirbnbBClone/node_modules/@apollo/react-hooks/lib/react-hooks.esm.js
Module not found: Can't resolve 'apollo-client' in '/home/foo/AirbnbBClone/node_modules/@apollo/react-hooks/lib'
```
I was wondering it it could be related to different versions between my code and those used in the video tutorial but I have not figured it out yet, though it looks like it is related with the Yarn workspace?

**Comment by benawad** [comment]
> it could be related to different versions between my code and those used in the video tutorial

That's most likely it, you'll want to use `@apollo/client` now
