### ISSUE TITLE
codegen

### ISSUE THREAD

**Issue by 4ware** [benawad/fullstack-graphql-airbnb-clone#7]
Hi!

I'm running codegen in my controller directory but i get the following error. What am i missing?

yarn codegen:generate
yarn run v1.7.0
$ apollo codegen:generate --queries=./src/**/*.tsx --schema=./schema.json --target=typescript ./src/schemaTypes.ts
 ›   Error: For TypeScript and Flow generators, "output" must be empty or a single directory name, unless the "outputFlat" flag is set.
error Command failed with exit code 2.

**Comment by benawad** [comment]
try: `apollo codegen:generate --queries=./src/**/*.tsx --schema=./schema.json --target=typescript --outputFlat ./src/schemaTypes.ts

**Comment by 4ware** [comment]
Thanks! Thats it!!!
