### ISSUE TITLE
[request] A nicer README for getting started with the clone

### ISSUE THREAD

**Issue by merelinguist** [benawad/fullstack-graphql-airbnb-clone#9]
This clone is a really nice boilerplate for starting a graphql app, but it would be really useful if you could write some docs to get started (what to install / what to commands to run etc).

**Comment by benawad** [comment]
Yeah adding some docs would be a good idea, not sure when I'll get to it though

**Comment by benawad** [comment]
I added some information in the readme, let me know if there's anything else you would like to see documentation on.
